<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>

        <AssemblyName>NBTLoupe</AssemblyName>
        <Version>0.0.0</Version>
        <ApplicationIcon>Assets/NBTLoupe.ico</ApplicationIcon>

        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <PublishAot>true</PublishAot>
        <OptimizationPreference>Speed</OptimizationPreference>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.1"/>
        <PackageReference Include="Avalonia.Desktop" Version="12.1.1"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1"/>
        <PackageReference Include="Avalonia.Wayland" Version="12.1.1"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2"/>
        <PackageReference Include="FluentIcons.Avalonia" Version="2.1.337"/>
        <PackageReference Include="Serilog" Version="4.4.0"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1"/>
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NBTModel\NBTModel.csproj"/>
    </ItemGroup>

    <Target Name="CopyIcons" BeforeTargets="BeforeBuild">
        <ItemGroup>
            <Icons Include="..\ASSETS\icons\NBTLoupe.png;..\ASSETS\icons\NBTLoupe.ico"/>
        </ItemGroup>
        <Copy SourceFiles="@(Icons)" DestinationFolder="$(MSBuildProjectDirectory)\Assets" SkipUnchangedFiles="true"/>
    </Target>

    <ItemGroup>
        <AvaloniaResource Include="Assets\NBTLoupe.ico"/>
        <AvaloniaResource Include="Assets\NBTLoupe.png"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="App.axaml.cs">
            <DependentUpon>App.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\MainWindow.axaml.cs">
            <DependentUpon>MainWindow.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Main\MainView.axaml.cs">
            <DependentUpon>MainView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Main\MainMenuView.axaml.cs">
            <DependentUpon>MainMenuView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Main\MainCommandBarView.axaml.cs">
            <DependentUpon>MainCommandBarView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Main\MainTreeViewView.axaml.cs">
            <DependentUpon>MainTreeViewView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Main\MainSearchBarView.axaml.cs">
            <DependentUpon>MainSearchBarView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Dialogs\DialogHostViewModel.axaml.cs">
            <DependentUpon>DialogHostViewModel.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Dialogs\AboutDialogView.axaml.cs">
            <DependentUpon>AboutDialogView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Dialogs\AddTagDialogView.axaml.cs">
            <DependentUpon>AddTagDialogView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Dialogs\ChunkFinderDialogView.axaml.cs">
            <DependentUpon>ChunkFinderDialogView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Dialogs\EditTagDialogView.axaml.cs">
            <DependentUpon>EditTagDialogView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Dialogs\ErrorDialogView.axaml.cs">
            <DependentUpon>ErrorDialogView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Dialogs\FindBasicDialogView.axaml.cs">
            <DependentUpon>FindBasicDialogView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Dialogs\FindAdvancedDialogView.axaml.cs">
            <DependentUpon>FindAdvancedDialogView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Dialogs\InfoDialogView.axaml.cs">
            <DependentUpon>InfoDialogView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Dialogs\UnsavedChangesDialogView.axaml.cs">
            <DependentUpon>UnsavedChangesDialogView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Core\TreeNodes\TreeNodes.Expansion.Cs">
            <DependentUpon>TreeNodes.cs</DependentUpon>
        </Compile>
        <Compile Update="ViewModels\Main\MainViewModel.Blocking.cs">
            <DependentUpon>MainViewModel.cs</DependentUpon>
        </Compile>
        <Compile Update="ViewModels\Main\MainViewModel.CommandChecks.cs">
            <DependentUpon>MainViewModel.cs</DependentUpon>
        </Compile>
        <Compile Update="ViewModels\Main\MainViewModel.Commands.cs">
            <DependentUpon>MainViewModel.cs</DependentUpon>
        </Compile>
        <Compile Update="ViewModels\Main\MainViewModel.Dialogs.cs">
            <DependentUpon>MainViewModel.cs</DependentUpon>
        </Compile>
    </ItemGroup>
</Project>
