#!/bin/sh
#
# Copyright (c) 2004-20 Simon Peter
# SPDX-License-Identifier: MIT
#
# Derived from https://github.com/AppImage/AppImageKit/wiki/Bundling-.NET-Core-apps
#

HERE="$(dirname "$(readlink -f "${0}")")"
exec "${HERE}/usr/bin/NBTLoupe" "$@"
